language: python
python:
  - "2.7"
# command to install dependencies
before_install:
 - sudo apt-get install --yes --force-yes libevent-dev

install:
  - pip install -e .[test]
  - pip install coveralls --use-mirrors
# command to run tests
script:
  - nosetests
  - coverage run --source=airbrake-flask setup.py nosetests
after_success:
  - coveralls
