language: python

python:
  - "2.7"

# command to install dependencies
before_install:
 - sudo apt-get install --yes --force-yes libevent-dev

install:
  - pip install -e .[test]
  - pip install coveralls --use-mirrors

# command to run tests
script:
  - make test
  - coverage run setup.py nosetests --with-coverage --cover-package=airbrake
after_success:
  - coveralls
