language: python
python:
  - "2.7"

# command to install dependencies
before_install:
 - sudo apt-get install --yes --force-yes libevent-dev

install:
  - pip install -e .[test]
  - pip install coveralls --use-mirrors

# command to run tests
script:
  - make test
  - make cover
  - coverage run --source=airbrake-flask setup.py nosetests -s -v --with-coverage --cover-html --cover-html-dir ./coverage
after_success:
  - coveralls
